### PR TITLE
Add CI status and link

### PR DESCRIPTION
**Pull request by notFloran**
Related to #15 

Capture d’écran 2019-07-05 à 18 21 49

### CODE REVIEW

**Comment by nclsHart** [comment]
For a first version, we could use the same color as the :+1: and :-1: badges.

After a quick test I got this result:

ci-badge

Using the following classes:

```html
<a class="bg-green-500 text-white p-2 rounded shadow hover:bg-green-600 font-bold">
    success
</a>
```

**Comment by notFloran** [comment]
We can take inspiration from the Pill component

**Comment by notFloran** [comment]
@nclsHart An idea for the name of the component ? badge ? button ?

**Comment by nclsHart** [comment]
I'm ok with both `PipelineStatusButton` or `PipelineStatusBadge`.

**Comment by notFloran** [comment]
ping @nclsHart @TomBerriot

**Comment by nclsHart** [comment]
@notFloran tslint reported 2 errors in the last build.

**Comment by notFloran** [comment]
I fix the two errors

**Pull request merged**
